/*
editorcoder
SRJC CS55.13 Fall 2025
Week 14: Assignment 14: Final Headless CMS-Powered App 
ExtendedLore.jsx
2025-11-22
*/

// NOTE: This component is currently NOT IN USE.
// It has been deactivated and may be reactivated in a future release.
// All references to this component have been commented out in the page.js files.

// ExtendedLore component

// Mark this file as a client component
"use client";

// Import React hooks
import { useState } from "react";
// Import generateExtendedLore server action
import { generateExtendedLore } from "@/lib/actions/geminiActions";
// Import ExtendedLore CSS styles
import styles from "./ExtendedLore.module.css";

// Skeleton component for displaying loading state while extended lore is being generated
export function ExtendedLoreSkeleton() {
  return (
    <div>
      <h4>Extended Lore</h4>
      <p>✨ Generating extended lore with Gemini...</p>
    </div>
  );
}

// Component for displaying lore with Extended/extended lore option
export default function ExtendedLore({ lore, cardId, mechanics, title }) {
  // State to track whether extended lore is currently displayed
  const [showExtended, setShowExtended] = useState(false);
  // State to store the extended lore text
  const [extendedLore, setExtendedLore] = useState(null);
  // State to track loading status
  const [isLoading, setIsLoading] = useState(false);

  // Handler for Extended Lore button click
  const handleShowExtended = async () => {
    // If extended lore is already loaded, just show it
    if (extendedLore) {
      setShowExtended(true);
      return;
    }

    // Set loading state
    setIsLoading(true);
    
    try {
      // Call server action to generate extended lore
      const generatedLore = await generateExtendedLore(cardId, lore, mechanics, title);
      // Store the extended lore text
      setExtendedLore(generatedLore);
      // Show extended lore view
      setShowExtended(true);
    } catch (error) {
      // Log error for debugging
      console.error('Error generating extended lore:', error);
      // Set placeholder text on error
      setExtendedLore('✨ Generating extended lore with Gemini...');
      // Show extended lore view even on error
      setShowExtended(true);
    } finally {
      // Set loading state to false
      setIsLoading(false);
    }
  };

  // Handler for Lore button click (restore original)
  const handleShowOriginal = () => {
    setShowExtended(false);
  };

  // Render extended lore view
  if (showExtended) {
    // Show skeleton component while loading
    if (isLoading) {
      return <ExtendedLoreSkeleton />;
    }
    
    return (
      <div>
        <h4>Extended Lore</h4>
        <p>
          {extendedLore}<br/>
          [✨ Generated by Gemini]
        </p>
        <button
          onClick={handleShowOriginal}
          className={styles.loreButton}
        >
          🧠 Original Lore
        </button>
      </div>
    );
  }

  // Render original lore view
  return (
    <div>
      <h4>Lore</h4>
      <p>
        {lore}
      </p>
      <button
        onClick={handleShowExtended}
        disabled={isLoading}
        className={styles.ExtendedLoreButton}
      >
        🤖 Extended Lore
      </button>
    </div>
  );
}

